### ISSUE TITLE
f-strings fail linter.

### ISSUE THREAD

**Issue by hadrien** [dreadatour/Flake8Lint#106]
Due to old version of pyflake

```bash 
$ echo "foo = f'{bar}'" | python lint.py --pyflakes
Traceback (most recent call last):
  File "lint.py", line 405, in <module>
    for lint_warning in lint(stdin_lines, lint_settings):
  File "lint.py", line 238, in lint
    w = pyflakes_checker.Checker(tree)
  File "contrib/pyflakes/checker.py", line 294, in __init__
    self.handleChildren(tree)
  File "contrib/pyflakes/checker.py", line 567, in handleChildren
    self.handleNode(node, tree)
  File "contrib/pyflakes/checker.py", line 609, in handleNode
    handler(node)
  File "contrib/pyflakes/checker.py", line 567, in handleChildren
    self.handleNode(node, tree)
  File "contrib/pyflakes/checker.py", line 608, in handleNode
    handler = self.getNodeHandler(node.__class__)
  File "contrib/pyflakes/checker.py", line 462, in getNodeHandler
    self._nodeHandlers[node_class] = handler = getattr(self, nodeType)
AttributeError: 'Checker' object has no attribute 'JOINEDSTR'
```

**Comment by hadrien** [comment]
With the fix: 
```bash
$ echo "foo = f'{bar}'" | python lint.py --pyflakes
1:1:F821 undefined name 'bar'
```
