### ISSUE TITLE
Flake8Lint stopped working randomly

### ISSUE THREAD

**Issue by bastula** [dreadatour/Flake8Lint#61]
Hello,

Flake8Lint stopped working for me suddenly. I am using Sublime Text 3 build 3065 on Windows and version 1.2.0 of Flake8Lint.

Got a traceback from the ST console with the following when saving a file:

```Python
Flake8Lint ERROR: Traceback (most recent call last):
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\lint.py", line 292, in <module>
Flake8Lint ERROR: for warning in lint(filename, settings):
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\lint.py", line 181, in lint
Flake8Lint ERROR: pyflakes.api.checkPath(filename, flakes_reporter)
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\contrib\pyflakes\api.py", line 86, in checkPath
Flake8Lint ERROR: return check(codestr, filename, reporter)
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\contrib\pyflakes\api.py", line 58, in check
Flake8Lint ERROR: w = checker.Checker(tree, filename)
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\contrib\pyflakes\checker.py", line 253, in __init__
Flake8Lint ERROR: self.handleChildren(tree)
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\contrib\pyflakes\checker.py", line 520, in handleChildren
Flake8Lint ERROR: self.handleNode(node, tree)
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\contrib\pyflakes\checker.py", line 555, in handleNode
Flake8Lint ERROR: handler(node)
Flake8Lint ERROR: File "C:\Users\bastula\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\contrib\pyflakes\checker.py", line 779, in CLASSDEF
Flake8Lint ERROR: for keywordNode in node.keywords:
Flake8Lint ERROR: AttributeError: 'ClassDef' object has no attribute 'keywords'
```

The package was working previously and stopped working without any indication.

**Comment by dreadatour** [comment]
Pull request was merged. Sorry for a long answer.
