### ISSUE TITLE
Flake8Lint 1.5.1 IndentationError on ST2&ST3

### ISSUE THREAD

**Issue by ipfans** [dreadatour/Flake8Lint#65]
on ST3(or ST2):

```
Flake8Lint ERROR: Traceback (most recent call last):
Flake8Lint ERROR: File "/Users/xxxx/Library/Application Support/Sublime Text 3/Packages/Python Flake8 Lint/lint.py", line 310, in <module>
Flake8Lint ERROR: for warning in lint(filename, settings):
Flake8Lint ERROR: File "/Users/xxxx/Library/Application Support/Sublime Text 3/Packages/Python Flake8 Lint/lint.py", line 201, in lint
Flake8Lint ERROR: tree = compile(lines, '', 'exec', ast.PyCF_ONLY_AST)
Flake8Lint ERROR: File "", line 212
Flake8Lint ERROR: lldb.debugger.GetCommandInterpreter().HandleCommand("settings set stop-disassembly-count 0", res);
Flake8Lint ERROR: ^
Flake8Lint ERROR: IndentationError: unexpected indent
```

It seems that on spacial files will got a error. like: https://github.com/deroko/lldbinit/blob/master/lldbinit.py

**Comment by dreadatour** [comment]
Fixed, thank you!
