### ISSUE TITLE
Linting not working

### ISSUE THREAD

**Issue by stevenh** [dreadatour/Flake8Lint#91]
I installed with Package control and it all seems to install correctly but linting fails.

The console with debug enabled shows:
```python
[Flake8Lint DEBUG] update statusbar
[Flake8Lint DEBUG] run flake8 lint
[Flake8Lint DEBUG] skip view: filename is empty
[Flake8Lint DEBUG] update statusbar
[Flake8Lint DEBUG] run flake8 lint
[Flake8Lint DEBUG] ignore file patterns: ['.git', 'contrib']
[Flake8Lint DEBUG] python interpreter: auto
[Flake8Lint DEBUG] interpreter is external
[Flake8Lint DEBUG] guess interpreter: 'pythonw'
[Flake8Lint DEBUG] linter file: C:\Users\XXXX\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\lint.py
[Flake8Lint DEBUG] interpreter is external
Traceback (most recent call last):
  File "./subprocess.py", line 1112, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\Flake8Lint.py", line 1164, in <lambda>
    lambda: Flake8Lint.async_lint(view, view_settings, quiet=quiet), 0
  File "C:\Users\XXXX\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\Flake8Lint.py", line 1221, in async_lint
    interpreter, linter)
  File "C:\Users\XXXX\AppData\Roaming\Sublime Text 3\Packages\Python Flake8 Lint\lint.py", line 347, in lint_external
    startupinfo=startupinfo
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1118, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Looks like its looking for a python interpreter but the install docs don't mention any requirement on this, did I miss something?

**Comment by stevenh** [comment]
Installing python for windows solved the issue, but still odd that its not mentioned as a requirement especially as it seems to be able to run python code otherwise it wouldn't have got that far.
